import type { Metadata } from "next";
import Head from 'next/head';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Playfair_Display, Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

// Configura Playfair Display per i titoli
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  weight: ['400', '600', '700'], // Specifica i pesi necessari
  display: 'swap', // Migliora CLS (Cumulative Layout Shift)
});

// Configura Atlas Grotesk (usando Inter come fallback)
const atlas = Inter({
  subsets: ['latin'],
  variable: '--font-atlas',
  weight: ['400', '500'],
  display: 'swap',
});

export default function RootLayout({
children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${atlas.variable}`}>
      <body className="font-sans">
        <Navbar/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
